urls:
  api: 'https://api.multiversx.com'
  redis: '127.0.0.1'
features:
  cacheWarmer:
    enabled: true
    port: 5201
  privateApi:
    enabled: true
    port: 4000
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgqvhk2wnx5tgzvlalzdt7yus5ygue084hx7j4qka2gz6'
