urls:
  api: 'https://devnet-api.multiversx.com'
  redis: '127.0.0.1'
features:
  cacheWarmer:
    enabled: true
    port: 5201
  privateApi:
    enabled: false
    port: 4000
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgqrsse0535l7f0rtp7e8t560tws2g3y0aq7j4qa2cl30'
