chainId: 'D'
urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'http://localhost:3000'
    - 'https://devnet-microservice.multiversx.com'
  redis: '127.0.0.1'
database:
  host: 'localhost'
  port: 27017
  name: 'example'
features:
  publicApi:
    enabled: true
    port: 3001
  privateApi:
    enabled: true
    port: 4001
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - http://localhost:3000
    - https://localhost:3001
    - https://localhost:3002
    - https://utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgq2kyfdk57vf8z4uht3c25wuz8gu7n0mck7j4q58f7s7'
