urls:
  api: 'https://api.multiversx.com'
  redis: '127.0.0.1'
features:
  transactionProcessor:
    port: 5202
    maxLookBehind: 100
  privateApi:
    enabled: true
    port: 4000
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgq2kyfdk57vf8z4uht3c25wuz8gu7n0mck7j4q58f7s7'
