urls:
  api: 'https://devnet-api.multiversx.com'
  redis: '127.0.0.1'
features:
  transactionProcessor:
    port: 5202
    maxLookBehind: 100
  privateApi:
    enabled: true
    port: 4000
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgqrsse0535l7f0rtp7e8t560tws2g3y0aq7j4qa2cl30'
