urls:
  api: 'https://testnet-api.multiversx.com'
  redis: '127.0.0.1'
features:
  transactionProcessor:
    port: 5202
    maxLookBehind: 100
  privateApi:
    enabled: true
    port: 4000
contracts:
  xCoffee: 'erd1qqqqqqqqqqqqqpgqvhk2wnx5tgzvlalzdt7yus5ygue084hx7j4qka2gz6'
